#!/usr/bin/perl -w --
#
# generated by wxGlade 1.1.1 on Thu Feb 26 14:48:17 2026
# UPDATED: non-blocking "Find DLLs" runs pp (autolink scan) in a worker thread and streams output to txt_cmd_io
#
# To get wxPerl visit http://www.wxperl.it
#

use strict;
use warnings;

use Wx;
use threads;
use Thread::Queue;
use Cwd;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw(:everything);
use base qw(Wx::Frame);
use strict;
use warnings;

sub new {
    my( $class, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyFrame::new
    $style = wxCAPTION|wxCLIP_CHILDREN|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU
        unless defined $style;

    my $self = $class->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1008, 596));
    $self->SetTitle("wxPerl GUI Helper for Windows By Perl-Guilds.net");

    # Menu Bar
    $self->{frame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;

    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{menu_open_pl} = $wxglade_tmp_menu->Append(wxID_ANY, "Open (.pl) ...", "");
    $self->{Exit} = $wxglade_tmp_menu->Append(wxID_ANY, "Exit", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "File");

    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{Aboutt} = $wxglade_tmp_menu->Append(wxID_ANY, "About", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "Help");

    $self->SetMenuBar($self->{frame_menubar});
    # Menu Bar end

    $self->{panel_1} = Wx::Panel->new($self, wxID_ANY);

    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);

    $self->{notebook_1} = Wx::Notebook->new($self->{panel_1}, wxID_ANY);
    $self->{sizer_1}->Add($self->{notebook_1}, 1, wxEXPAND, 0);

    # -------- Pane 1: EXE Builder --------
    $self->{notebook_1_pane_1} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_1}, "EXE Builder");

    $self->{sizer_2} = Wx::FlexGridSizer->new(2, 2, 0, 0);
    $self->{sizer_2}->Add(0, 0, 0, 0, 0);

    $self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_2}->Add($self->{sizer_4}, 1, wxEXPAND, 0);

    my $lbl_pl = Wx::StaticText->new($self->{notebook_1_pane_1}, wxID_ANY, "Perl Script:");
    $self->{sizer_4}->Add($lbl_pl, 0, 0, 0);

    $self->{perl_script_path} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "");
    $self->{perl_script_path}->SetMinSize(Wx::Size->new(740, 23));
    $self->{sizer_4}->Add($self->{perl_script_path}, 1, wxEXPAND|wxLEFT|wxRIGHT, 6);

    $self->{sizer_4}->Add(0, 0, 0, 0, 0);

    $self->{button_browse_pl} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Browse\N{U+2026}");
    $self->{sizer_4}->Add($self->{button_browse_pl}, 0, wxEXPAND, 0);

    $self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_2}->Add($self->{sizer_3}, 1, wxEXPAND, 0);

    $self->{button_3} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Find DLLs");
    $self->{button_3}->SetToolTip("Runs pp (autolink scan) to find the DLLs needed");
    $self->{sizer_3}->Add($self->{button_3}, 0, wxEXPAND, 0);

    $self->{button_2} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Verify Env");
    $self->{button_2}->SetToolTip("Verifies that you are running this via Strawberry Perl and that the required modules are installed.");
    $self->{sizer_3}->Add($self->{button_2}, 0, wxEXPAND, 0);

    $self->{button_6} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Exit");
    $self->{sizer_3}->Add($self->{button_6}, 0, wxEXPAND, 0);

    $self->{txt_cmd_io} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_BESTWRAP|wxTE_MULTILINE|wxTE_RICH2);
    $self->{txt_cmd_io}->SetMinSize(Wx::Size->new(800, 496));
    $self->{sizer_2}->Add($self->{txt_cmd_io}, 1, wxEXPAND, 0);

    # -------- Pane 2: Installer Creator --------
    $self->{notebook_1_pane_2} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_2}, "Installer Creator");

    $self->{sizer_inno_main} = Wx::BoxSizer->new(wxVERTICAL);

    $self->{sizer_iscc} = Wx::StaticBoxSizer->new(
        Wx::StaticBox->new($self->{notebook_1_pane_2}, wxID_ANY, "ISCC.exe"),
        wxHORIZONTAL
    );
    $self->{sizer_inno_main}->Add($self->{sizer_iscc}, 0, wxALL|wxEXPAND, 10);

    $self->{txt_iscc_path} = Wx::TextCtrl->new(
        $self->{sizer_iscc}->GetStaticBox(),
        wxID_ANY,
        "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe"
    );
    $self->{sizer_iscc}->Add($self->{txt_iscc_path}, 1, wxEXPAND|wxRIGHT, 6);

    $self->{btn_browse_iscc} = Wx::Button->new($self->{sizer_iscc}->GetStaticBox(), wxID_ANY, "Browse\N{U+2026}");
    $self->{sizer_iscc}->Add($self->{btn_browse_iscc}, 0, 0, 0);

    $self->{sizer_inno_opts} = Wx::StaticBoxSizer->new(
        Wx::StaticBox->new($self->{notebook_1_pane_2}, wxID_ANY, "Options"),
        wxVERTICAL
    );
    $self->{sizer_inno_main}->Add($self->{sizer_inno_opts}, 0, wxBOTTOM|wxLEFT|wxRIGHT, 10);

    $self->{chk_inno_quiet} = Wx::CheckBox->new($self->{sizer_inno_opts}->GetStaticBox(), wxID_ANY, "Quiet compile (/Q)");
    $self->{chk_inno_quiet}->SetValue(1);
    $self->{sizer_inno_opts}->Add($self->{chk_inno_quiet}, 0, wxALL, 4);

    $self->{chk_inno_open_output} = Wx::CheckBox->new($self->{sizer_inno_opts}->GetStaticBox(), wxID_ANY, "Open output folder after build");
    $self->{sizer_inno_opts}->Add($self->{chk_inno_open_output}, 0, wxALL, 4);

    $self->{chk_inno_run_installer} = Wx::CheckBox->new($self->{sizer_inno_opts}->GetStaticBox(), wxID_ANY, "Run installer after build");
    $self->{sizer_inno_opts}->Add($self->{chk_inno_run_installer}, 0, wxALL, 4);

    $self->{sizer_inno_notes} = Wx::StaticBoxSizer->new(
        Wx::StaticBox->new($self->{notebook_1_pane_2}, wxID_ANY, "Notes / Defines (optional)"),
        wxVERTICAL
    );
    $self->{sizer_inno_main}->Add($self->{sizer_inno_notes}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 10);

    $self->{txt_inno_defines} = Wx::TextCtrl->new(
        $self->{sizer_inno_notes}->GetStaticBox(),
        wxID_ANY,
        "",
        wxDefaultPosition,
        wxDefaultSize,
        wxHSCROLL|wxTE_MULTILINE
    );
    $self->{sizer_inno_notes}->Add($self->{txt_inno_defines}, 1, wxALL|wxEXPAND, 6);

    # -------- Pane 3: Help --------
    $self->{notebook_1_pane_3} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_3}, "Help");

    $self->{notebook_1_pane_2}->SetSizer($self->{sizer_inno_main});
    $self->{notebook_1_pane_1}->SetSizer($self->{sizer_2});
    $self->{panel_1}->SetSizer($self->{sizer_1});

    # ----- background worker comms -----
    $self->{_q}     = Thread::Queue->new();
    $self->{_timer} = Wx::Timer->new($self, wxID_ANY);
    Wx::Event::EVT_TIMER($self, $self->{_timer}, sub { $self->_drain_worker_queue });
    $self->{_timer}->Start(100); # 100ms poll
    # -----------------------------------

    $self->Layout();

    Wx::Event::EVT_MENU($self, $self->{Exit}->GetId,      $self->can('DoQuit'));
    Wx::Event::EVT_MENU($self, $self->{Aboutt}->GetId,    $self->can('show_license_dialog'));
    Wx::Event::EVT_MENU($self, $self->{menu_open_pl}->GetId, $self->can('select_perl_script'));

    Wx::Event::EVT_BUTTON($self, $self->{button_browse_pl}->GetId, $self->can('select_perl_script'));
    Wx::Event::EVT_BUTTON($self, $self->{button_3}->GetId,         $self->can('run_pp_autolink'));
    Wx::Event::EVT_BUTTON($self, $self->{button_2}->GetId,         $self->can('verify_env'));
    Wx::Event::EVT_BUTTON($self, $self->{button_6}->GetId,         $self->can('DoQuit'));

    # end wxGlade
    return $self;
}

sub _append_io {
    my ($self, $text) = @_;
    return unless defined $text && length $text;

    $self->{txt_cmd_io}->AppendText($text);
    $self->{txt_cmd_io}->ShowPosition($self->{txt_cmd_io}->GetLastPosition);
}

sub _drain_worker_queue {
    my ($self) = @_;
    my $q = $self->{_q} or return;

    while (defined(my $msg = $q->dequeue_nb)) {
        if (ref($msg) eq 'HASH' && ($msg->{type} // '') eq 'DONE') {
            $self->_append_io("\n[done] exit_code=$msg->{exit_code}\n");
            $self->{button_3}->Enable(1);
            next;
        }
        $self->_append_io($msg);
    }
}

sub DoQuit {
    my ($self, $event) = @_;
    $self->Close(1);
}

sub show_license_dialog {
    my ($self, $event) = @_;
    my $msg = "wxPerl GUI Helper for Windows\n\n(c) Perl-Guilds.net\n";
    Wx::MessageBox($msg, "About", wxOK|wxICON_INFORMATION, $self);
}

sub select_perl_script {
    my ($self, $event) = @_;

    my $dlg = Wx::FileDialog->new(
        $self,
        "Select Perl Script",
        "", "",
        "Perl files (*.pl)|*.pl|All files (*.*)|*.*",
        Wx::wxFD_OPEN() | Wx::wxFD_FILE_MUST_EXIST()
    );

    if ($dlg->ShowModal == Wx::wxID_OK()) {
        my $path = $dlg->GetPath;  # full path
        $self->{perl_script_path}->SetValue($path);
        $self->_append_io("Selected: $path\n");
    }

    $dlg->Destroy;
}

sub run_pp_autolink {
    my ($self, $event) = @_;

    my $script = $self->{perl_script_path}->GetValue // '';
    $script =~ s/^\s+|\s+$//g;

    $self->_append_io("\n[debug] Find DLLs clicked\n");

    if (!$script) {
        $self->_append_io("[error] No .pl selected.\n");
        return;
    }
    if (!-f $script) {
        $self->_append_io("[error] File not found: $script\n");
        return;
    }

    $script = Cwd::abs_path($script) || $script;
    $self->_append_io("[debug] script resolved to: $script\n");

    $self->{button_3}->Enable(0);
    $self->_append_io("=== Starting pp autolink scan ===\n");

    my $q = $self->{_q};

    threads->create(sub {
        my ($script_path, $qref) = @_;

        $qref->enqueue("[worker] thread started\n");

        # Check pp is runnable
        my $pp_ver = `pp --version 2>&1`;
        my $pp_rc  = $? >> 8;
        $qref->enqueue("[worker] pp --version rc=$pp_rc\n$pp_ver\n");

        if ($pp_rc != 0) {
            $qref->enqueue("[worker][error] 'pp_autolink' command failed. Is PAR::Packer installed and on PATH?\n");
            $qref->enqueue({ type => 'DONE', exit_code => $pp_rc });
            return;
        }

        my @cmd = qw/pp_autolink -o tmp.exe/;
        push @cmd, $script_path;

        my $pretty = join(' ', map { $_ =~ /\s/ ? qq{"$_"} : $_ } @cmd);
        $qref->enqueue("[worker] cmd: $pretty\n");

        my $cmdline = $pretty . " 2>&1";

        my $exit = 0;
        if (open(my $fh, "$cmdline |")) {
            $qref->enqueue("[worker] pipe opened, reading output...\n");

            my $line_count = 0;
            while (my $line = <$fh>) {
                $line_count++;
                $qref->enqueue($line);
            }

            close($fh);
            $exit = $? >> 8;
            $qref->enqueue("[worker] pipe closed, lines=$line_count, rc=$exit\n");
        } else {
            $qref->enqueue("[worker][error] failed to run command pipe: $!\n");
            $exit = 127;
        }

        $qref->enqueue({ type => 'DONE', exit_code => $exit });
        return;
    }, $script, $q)->detach();

    $self->_append_io("[debug] worker thread launched\n");
}

sub verify_env {
    my ($self, $event) = @_;

    $self->_append_io("\n=== Verify Env ===\n");

    my $perl = $^X // 'perl';
    $self->_append_io("perl: $perl\n");

    my $pp = `pp --version 2>&1`;
    if ($? == 0) {
        $self->_append_io("pp: $pp\n");
    } else {
        $self->_append_io("[warn] pp not found or failed: $pp\n");
    }

    my $wx = $Wx::VERSION // '(unknown)';
    $self->_append_io("Wx::VERSION: $wx\n");
}

# end of class MyFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;
use warnings;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame = MyFrame->new();
    $self->SetTopWindow($frame);
    $frame->Show(1);

    return 1;
}

package main;

my $app = MyApp->new();
$app->MainLoop();
