#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Sat Feb 28 01:02:48 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use strict;
use warnings;

use Wx;
use threads;
use Thread::Queue;
use File::Spec;
use Cwd;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyFrame::new
    $style = wxCAPTION|wxCLIP_CHILDREN|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(800, 500));
    $self->SetTitle("wxPerl GUI Helper for Windows By Perl-Guilds.net");
    
    

    # Menu Bar

    $self->{frame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{Open} = $wxglade_tmp_menu->Append(wxID_ANY, "Open (.pl) ...", "");
    $self->{Exit} = $wxglade_tmp_menu->Append(wxID_ANY, "Exit", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "File");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{Aboutt} = $wxglade_tmp_menu->Append(wxID_ANY, "About", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "Help");
    $self->SetMenuBar($self->{frame_menubar});
    
    # Menu Bar end

    
    $self->{panel_1} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{notebook_1} = Wx::Notebook->new($self->{panel_1}, wxID_ANY);
    $self->{sizer_1}->Add($self->{notebook_1}, 1, wxEXPAND, 0);
    
    $self->{notebook_1_pane_1} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_1}, "DLL Finder/Makefile Generator");
    
    $self->{sizer_2} = Wx::FlexGridSizer->new(2, 2, 0, 0);
    
    my $label_1 = Wx::StaticText->new($self->{notebook_1_pane_1}, wxID_ANY, "Source (.pl)");
    $self->{sizer_2}->Add($label_1, 0, wxALIGN_CENTER, 0);
    
    $self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_2}->Add($self->{sizer_4}, 1, wxEXPAND, 0);
    
    $self->{perl_script_path} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "");
    $self->{perl_script_path}->SetMinSize(Wx::Size->new(444, 23));
    $self->{sizer_4}->Add($self->{perl_script_path}, 1, wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{button_browse_pl} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Browse\N{U+2026}");
    $self->{sizer_4}->Add($self->{button_browse_pl}, 0, wxEXPAND, 0);
    
    $self->{button_3} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Find DLLs");
    $self->{button_3}->SetToolTip("Runs pp_autolink to find the DLLs needed");
    $self->{sizer_4}->Add($self->{button_3}, 0, wxEXPAND, 0);
    
    $self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_2}->Add($self->{sizer_3}, 1, wxEXPAND, 0);
    
    $self->{sizer_3}->Add(73, 200, 0, 0, 0);
    
    $self->{sizer_3}->Add(73, 200, 0, 0, 0);
    
    $self->{txt_cmd_io} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_BESTWRAP|wxTE_MULTILINE|wxTE_RICH2);
    $self->{txt_cmd_io}->SetMinSize(Wx::Size->new(800, 1100));
    $self->{sizer_2}->Add($self->{txt_cmd_io}, 1, wxALL|wxEXPAND, 3);
    
    $self->{notebook_1_pane_3} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_3}, "Inno Setup Compiler");
    
    $self->{notebook_1_Help} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_Help}, "Help");
    
    $self->{notebook_1_pane_1}->SetSizer($self->{sizer_2});
    
    $self->{panel_1}->SetSizer($self->{sizer_1});
    
    $self->Layout();
    Wx::Event::EVT_MENU($self, $self->{Open}->GetId, $self->can('select_perl_script'));
    Wx::Event::EVT_MENU($self, $self->{Exit}->GetId, $self->can('DoQuit'));
    Wx::Event::EVT_MENU($self, $self->{Aboutt}->GetId, $self->can('show_license_dialog'));
    Wx::Event::EVT_BUTTON($self, $self->{button_browse_pl}->GetId, $self->can('select_perl_script'));
    Wx::Event::EVT_BUTTON($self, $self->{button_3}->GetId, $self->can('run_pp_autolink'));

    # end wxGlade

    # ----- background worker comms -----
    $self->{_q}     = Thread::Queue->new();
    $self->{_timer} = Wx::Timer->new($self, wxID_ANY);
    Wx::Event::EVT_TIMER($self, $self->{_timer}, sub { $self->_drain_worker_queue });
    $self->{_timer}->Start(100); # 100ms poll
    # -----------------------------------
    return $self;

}

sub _append_io {
    my ($self, $text) = @_;
    return unless defined $text && length $text;

    $self->{txt_cmd_io}->AppendText($text);
    $self->{txt_cmd_io}->ShowPosition($self->{txt_cmd_io}->GetLastPosition);
}

sub _drain_worker_queue {
    my ($self) = @_;
    my $q = $self->{_q} or return;

    while (defined(my $msg = $q->dequeue_nb)) {
        if (ref($msg) eq 'HASH' && ($msg->{type} // '') eq 'DONE') {
            $self->_append_io("\n[done] exit_code=$msg->{exit_code}\n");
            $self->{button_3}->Enable(1);
            next;
        }
        $self->_append_io($msg);
    }
}

sub _get_perl_root {
    my $perl_path = $^X;  # full path to running perl.exe
    my ($volume, $dirs, $file) = File::Spec->splitpath($perl_path);
    my @parts = File::Spec->splitdir($dirs);
    
    # Remove \perl\bin\
    pop @parts; # bin
    pop @parts; # perl
    
    my $perl_root = File::Spec->catdir($volume, @parts);
    return $perl_root;
}

sub DoQuit {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::DoQuit <event_handler>
    # end wxGlade
    $self->Close;
}

sub show_license_dialog {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::show_license_dialog <event_handler>
    warn "Event handler (show_license_dialog) not implemented";
    $event->Skip;
    # end wxGlade
}

sub select_perl_script {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::select_perl_script <event_handler>
    # end wxGlade

    my $dlg = Wx::FileDialog->new(
        $self,
        "Select Perl Script",
        "", "",
        join('|',
            "Perl scripts (*.pl)", "*.pl",
            "Perl modules (*.pm)", "*.pm",
            "Extensionless files (*)", "*",
            "Perl-related (*.pl;*.pm;*)", "*.pl;*.pm;*",
            "All files (*.*)", "*.*",
        ),
        Wx::wxFD_OPEN() | Wx::wxFD_FILE_MUST_EXIST()
    );

    if ($dlg->ShowModal == Wx::wxID_OK()) {
        my $path = $dlg->GetPath;
        $self->{perl_script_path}->SetValue($path);
        $self->_append_io("Selected: $path\n");
    }

    $dlg->Destroy;
}

sub run_pp_autolink {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::run_pp_autolink <event_handler>
    # end wxGlade

    my $script = $self->{perl_script_path}->GetValue // '';
    $script =~ s/^\s+|\s+$//g;
    my $exe = $script;
    $exe =~ s/\.pl//g;
    $exe .= ".exe";

    $self->_append_io("\n[debug] Find DLLs clicked\n");

    if (!$script) {
        $self->_append_io("[error] No .pl selected.\n");
        return;
    }
    if (!-f $script) {
        $self->_append_io("[error] File not found: $script\n");
        return;
    }

    $script = Cwd::abs_path($script) || $script;
    $self->_append_io("[debug] script resolved to: $script\n");

    $self->{button_3}->Enable(0);
    $self->_append_io("\n=== Starting pp_ autolink scan ===\n\n");

    my $q = $self->{_q};

    threads->create(sub {
        my ($script_path, $qref) = @_;

        $qref->enqueue("[worker] thread started\n\n");

        # Check pp is runnable
        my $pp_ver = `pp --version 2>&1`;
        my $pp_rc  = $? >> 8;
        $qref->enqueue("[worker] pp --version rc=$pp_rc\n$pp_ver\n");

        if ($pp_rc != 0) {
            $qref->enqueue("[worker][error] 'pp_autolink' command failed. Is PAR::Packer installed and on PATH?\n");
            $qref->enqueue({ type => 'DONE', exit_code => $pp_rc });
            return;
        }

        my @cmd = qw/pp_autolink -o tmp.exe/;
        push @cmd, $script_path;

        my $pretty = join(' ', map { $_ =~ /\s/ ? qq{"$_"} : $_ } @cmd);
        $qref->enqueue("[worker] cmd: $pretty\n");

        my $cmdline = $pretty . " 2>&1";

        $qref->enqueue("\n\n=== Finding DLLs and generating Makefile ===\n\n");

        my $exit = 0;
        if (open(my $fh, "$cmdline |")) {
            $qref->enqueue("[worker] pipe opened, reading output...\n");

            my $line_count = 0;
            my $CMD_line = "";
            while (my $line = <$fh>) {
                $line_count++;
                $qref->enqueue($line);
                if ($line =~ m/^CMD:/) {
                  $CMD_line = $line;
                }
            }

            my $perl_path = $^X;  # full path to running perl.exe
            
            my ($volume, $dirs, $file) = File::Spec->splitpath($perl_path);
            my @parts = File::Spec->splitdir($dirs);
            
            # Remove \perl\bin\
            pop @parts;   # bin
            pop @parts;   # perl
            pop @parts;
            push @parts, "c", "bin";
            my $filter = $volume . join("/", @parts);
            my $perl_root = lc File::Spec->catdir($volume, @parts);
            my @cmd = split / /, $CMD_line;
            my @filtered_libs = grep { m/\Q$filter\E/i } @cmd;
            
            $qref->enqueue("\n\n=== Perl moduled DLLs to include ===\n\n");

            my $wxpar = "wxpar -o $exe";
            foreach my $lib (@filtered_libs) {
              $wxpar .= " --link $lib ";
              $qref->enqueue("$lib\n");
            }

            $wxpar .= " $script --gui";

            $qref->enqueue("\n\n=== Makefile with 'wxpar' command ===\n\n");
            
            $wxpar =~ s/\\/\//g;
            $wxpar =~ s/$filter/\$\(CBIN\)/gi;

            my $makefile = <<EOF;
CBIN    := "$perl_root"
DIST    := dist
RELEASE := release

clean:
	\@if exist dist\* del /Q /F dist\* 2>NUL
	\@if exist release\* del /Q /F release\* 2>NUL

all: exe

exe: prepdirs
	$wxpar
	\@move /Y $exe dist\

prepdirs:
	\@if not exist \$(DIST) mkdir \$(DIST)
	\@if not exist \$(RELEASE) mkdir \$(RELEASE)
EOF
            $qref->enqueue("$makefile\n\n");

            close($fh);
            $exit = $? >> 8;
            $qref->enqueue("[worker] pipe closed, lines=$line_count, rc=$exit\n");
        } else {
            $qref->enqueue("[worker][error] failed to run command pipe: $!\n");
            $exit = 127;
        }

        $qref->enqueue({ type => 'DONE', exit_code => $exit });
        return;
    }, $script, $q)->detach();

    $self->_append_io("[debug] worker thread launched\n");
}

# end of class MyFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame = MyFrame->new();

    $self->SetTopWindow($frame);
    $frame->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
