#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Thu Feb 26 14:48:17 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyFrame::new
    $style = wxCAPTION|wxCLIP_CHILDREN|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(1008, 596));
    $self->SetTitle("wxPerl GUI Helper for Windows By Perl-Guilds.net");
    
    

    # Menu Bar

    $self->{frame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $wxglade_tmp_menu->Append(wxID_ANY, "Open (.pl) ...", "");
    $self->{Exit} = $wxglade_tmp_menu->Append(wxID_ANY, "Exit", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "File");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{Aboutt} = $wxglade_tmp_menu->Append(wxID_ANY, "About", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "Help");
    $self->SetMenuBar($self->{frame_menubar});
    
    # Menu Bar end

    
    $self->{panel_1} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{notebook_1} = Wx::Notebook->new($self->{panel_1}, wxID_ANY);
    $self->{sizer_1}->Add($self->{notebook_1}, 1, wxEXPAND, 0);
    
    $self->{notebook_1_pane_1} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_1}, "EXE Builder");
    
    $self->{sizer_2} = Wx::FlexGridSizer->new(2, 2, 0, 0);
    
    $self->{sizer_2}->Add(0, 0, 0, 0, 0);
    
    $self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_2}->Add($self->{sizer_4}, 1, wxEXPAND, 0);
    
    my $lbl_pl = Wx::StaticText->new($self->{notebook_1_pane_1}, wxID_ANY, "Perl Script:");
    $self->{sizer_4}->Add($lbl_pl, 0, 0, 0);
    
    $self->{perl_script_path} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "");
    $self->{perl_script_path}->SetMinSize(Wx::Size->new(740, 23));
    $self->{sizer_4}->Add($self->{perl_script_path}, 1, wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{sizer_4}->Add(0, 0, 0, 0, 0);
    
    $self->{button_browse_pl} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Browse\N{U+2026}");
    $self->{sizer_4}->Add($self->{button_browse_pl}, 0, wxEXPAND, 0);
    
    $self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_2}->Add($self->{sizer_3}, 1, wxEXPAND, 0);
    
    $self->{button_3} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Find DLLs");
    $self->{button_3}->SetToolTip("Runs pp_autolink to find the DLLs needed");
    $self->{sizer_3}->Add($self->{button_3}, 0, wxEXPAND, 0);
    
    $self->{button_2} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Verify Env");
    $self->{button_2}->SetToolTip("Verifies that you are running this via Strawberry Perl and that the required modules are installed.");
    $self->{sizer_3}->Add($self->{button_2}, 0, wxEXPAND, 0);
    
    $self->{button_6} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Exit");
    $self->{sizer_3}->Add($self->{button_6}, 0, wxEXPAND, 0);
    
    $self->{txt_cmd_io} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxHSCROLL|wxTE_MULTILINE|wxTE_RICH2);
    $self->{txt_cmd_io}->SetMinSize(Wx::Size->new(800, 496));
    $self->{sizer_2}->Add($self->{txt_cmd_io}, 1, wxEXPAND, 0);
    
    $self->{notebook_1_pane_2} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_2}, "Installer Creator");
    
    $self->{sizer_inno_main} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{sizer_iscc} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{notebook_1_pane_2}, wxID_ANY, "ISCC.exe"), wxHORIZONTAL);
    $self->{sizer_inno_main}->Add($self->{sizer_iscc}, 0, wxALL|wxEXPAND, 10);
    
    $self->{txt_iscc_path} = Wx::TextCtrl->new($self->{sizer_iscc}->GetStaticBox(), wxID_ANY, "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe");
    $self->{sizer_iscc}->Add($self->{txt_iscc_path}, 1, wxEXPAND|wxRIGHT, 6);
    
    $self->{btn_browse_iscc} = Wx::Button->new($self->{sizer_iscc}->GetStaticBox(), wxID_ANY, "Browse\N{U+2026}");
    $self->{sizer_iscc}->Add($self->{btn_browse_iscc}, 0, 0, 0);
    
    $self->{sizer_inno_opts} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{notebook_1_pane_2}, wxID_ANY, "Options"), wxVERTICAL);
    $self->{sizer_inno_main}->Add($self->{sizer_inno_opts}, 0, wxBOTTOM|wxLEFT|wxRIGHT, 10);
    
    $self->{chk_inno_quiet} = Wx::CheckBox->new($self->{sizer_inno_opts}->GetStaticBox(), wxID_ANY, "Quiet compile (/Q)");
    $self->{chk_inno_quiet}->SetValue(1);
    $self->{sizer_inno_opts}->Add($self->{chk_inno_quiet}, 0, wxALL, 4);
    
    $self->{chk_inno_open_output} = Wx::CheckBox->new($self->{sizer_inno_opts}->GetStaticBox(), wxID_ANY, "Open output folder after build");
    $self->{sizer_inno_opts}->Add($self->{chk_inno_open_output}, 0, wxALL, 4);
    
    $self->{chk_inno_run_installer} = Wx::CheckBox->new($self->{sizer_inno_opts}->GetStaticBox(), wxID_ANY, "Run installer after build");
    $self->{sizer_inno_opts}->Add($self->{chk_inno_run_installer}, 0, wxALL, 4);
    
    $self->{sizer_inno_notes} = Wx::StaticBoxSizer->new(Wx::StaticBox->new($self->{notebook_1_pane_2}, wxID_ANY, "Notes / Defines (optional)"), wxVERTICAL);
    $self->{sizer_inno_main}->Add($self->{sizer_inno_notes}, 1, wxBOTTOM|wxEXPAND|wxLEFT|wxRIGHT, 10);
    
    $self->{txt_inno_defines} = Wx::TextCtrl->new($self->{sizer_inno_notes}->GetStaticBox(), wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxHSCROLL|wxTE_MULTILINE);
    $self->{sizer_inno_notes}->Add($self->{txt_inno_defines}, 1, wxALL|wxEXPAND, 6);
    
    $self->{notebook_1_pane_3} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_3}, "Help");
    
    $self->{notebook_1_pane_2}->SetSizer($self->{sizer_inno_main});
    
    $self->{notebook_1_pane_1}->SetSizer($self->{sizer_2});
    
    $self->{panel_1}->SetSizer($self->{sizer_1});
    
    $self->Layout();
    Wx::Event::EVT_MENU($self, $self->{Exit}->GetId, $self->can('DoQuit'));
    Wx::Event::EVT_MENU($self, $self->{Aboutt}->GetId, $self->can('show_license_dialog'));
    Wx::Event::EVT_BUTTON($self, $self->{button_browse_pl}->GetId, $self->can('select_perl_script'));
    Wx::Event::EVT_BUTTON($self, $self->{button_3}->GetId, $self->can('run_pp_autolink'));
    Wx::Event::EVT_BUTTON($self, $self->{button_2}->GetId, $self->can('verify_env'));
    Wx::Event::EVT_BUTTON($self, $self->{button_6}->GetId, $self->can('DoQuit'));

    # end wxGlade
    return $self;

}


sub DoQuit {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::DoQuit <event_handler>
    warn "Event handler (DoQuit) not implemented";
    $event->Skip;
    # end wxGlade
}


sub show_license_dialog {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::show_license_dialog <event_handler>
    warn "Event handler (show_license_dialog) not implemented";
    $event->Skip;
    # end wxGlade
}


sub select_perl_script {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::select_perl_script <event_handler>
    warn "Event handler (select_perl_script) not implemented";
    $event->Skip;
    # end wxGlade
}


sub run_pp_autolink {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::run_pp_autolink <event_handler>
    warn "Event handler (run_pp_autolink) not implemented";
    $event->Skip;
    # end wxGlade
}


sub verify_env {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::verify_env <event_handler>
    warn "Event handler (verify_env) not implemented";
    $event->Skip;
    # end wxGlade
}


# end of class MyFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame = MyFrame->new();

    $self->SetTopWindow($frame);
    $frame->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
