#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Sat Feb 28 01:02:48 2026
#
# To get wxPerl visit http://www.wxperl.it
#

use strict;
use warnings;

use Wx;
use threads;
use Thread::Queue;
use File::Spec;
use Cwd;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyFrame::new
    $style = wxCAPTION|wxCLIP_CHILDREN|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(800, 600));
    $self->SetTitle("wxPerl GUI Helper for Windows By Perl-Guilds.net");
    
    

    # Menu Bar

    $self->{frame_menubar} = Wx::MenuBar->new();
    my $wxglade_tmp_menu;
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{Open} = $wxglade_tmp_menu->Append(wxID_ANY, "Open (.pl) ...", "");
    $self->{Exit} = $wxglade_tmp_menu->Append(wxID_ANY, "Exit", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "File");
    $wxglade_tmp_menu = Wx::Menu->new();
    $self->{Aboutt} = $wxglade_tmp_menu->Append(wxID_ANY, "About", "");
    $self->{frame_menubar}->Append($wxglade_tmp_menu, "Help");
    $self->SetMenuBar($self->{frame_menubar});
    
    # Menu Bar end

    
    $self->{panel_1} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{notebook_1} = Wx::Notebook->new($self->{panel_1}, wxID_ANY);
    $self->{sizer_1}->Add($self->{notebook_1}, 1, wxEXPAND, 0);
    
    $self->{notebook_1_pane_1} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_1}, "DLL Finder/Makefile Generator");
    
    $self->{sizer_2} = Wx::FlexGridSizer->new(2, 2, 0, 0);
    
    my $label_1 = Wx::StaticText->new($self->{notebook_1_pane_1}, wxID_ANY, "Source (.pl)");
    $self->{sizer_2}->Add($label_1, 0, wxALIGN_CENTER, 0);
    
    $self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_2}->Add($self->{sizer_4}, 1, wxEXPAND, 0);
    
    $self->{perl_script_path} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "");
    $self->{perl_script_path}->SetMinSize(Wx::Size->new(444, 23));
    $self->{sizer_4}->Add($self->{perl_script_path}, 1, wxEXPAND|wxLEFT|wxRIGHT, 6);
    
    $self->{button_browse_pl} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Browse\N{U+2026}");
    $self->{sizer_4}->Add($self->{button_browse_pl}, 0, wxEXPAND, 0);
    
    $self->{button_3} = Wx::Button->new($self->{notebook_1_pane_1}, wxID_ANY, "Find DLLs");
    $self->{button_3}->SetToolTip("Runs pp_autolink to find the DLLs needed");
    $self->{sizer_4}->Add($self->{button_3}, 0, wxEXPAND, 0);
    
    $self->{sizer_3} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_2}->Add($self->{sizer_3}, 1, wxEXPAND, 0);
    
    $self->{sizer_3}->Add(73, 200, 0, 0, 0);
    
    $self->{sizer_3}->Add(73, 271, 0, 0, 0);
    
    $self->{txt_cmd_io} = Wx::TextCtrl->new($self->{notebook_1_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_BESTWRAP|wxTE_MULTILINE|wxTE_RICH2);
    $self->{txt_cmd_io}->SetMinSize(Wx::Size->new(800, 1100));
    $self->{sizer_2}->Add($self->{txt_cmd_io}, 1, wxALL|wxEXPAND, 3);
    
    $self->{notebook_1_pane_3} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_3}, "Inno Setup Compiler");
    
    $self->{iss_main_sizer} = Wx::BoxSizer->new(wxHORIZONTAL);
    
    $self->{iss_left_sizer} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{iss_main_sizer}->Add($self->{iss_left_sizer}, 0, wxALL|wxEXPAND, 6);
    
    my $iss_title = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Inno Setup (.iss) Generator");
    $self->{iss_left_sizer}->Add($iss_title, 0, wxEXPAND, 0);
    
    my $iss_line_1 = Wx::StaticLine->new($self->{notebook_1_pane_3}, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0);
    $self->{iss_left_sizer}->Add($iss_line_1, 0, wxEXPAND|wxTOP, 6);
    
    $self->{iss_form_grid} = Wx::FlexGridSizer->new(0, 2, 6, 8);
    $self->{iss_left_sizer}->Add($self->{iss_form_grid}, 0, wxEXPAND, 0);
    
    my $iss_lbl_appname = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "App Name");
    $self->{iss_form_grid}->Add($iss_lbl_appname, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_app_name} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "NHC Explorer");
    $self->{iss_form_grid}->Add($self->{iss_app_name}, 1, wxEXPAND, 0);
    
    my $iss_lbl_exe = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "App EXE");
    $self->{iss_form_grid}->Add($iss_lbl_exe, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_app_exe} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "nhc-explorer.exe");
    $self->{iss_form_grid}->Add($self->{iss_app_exe}, 1, wxEXPAND, 0);
    
    my $iss_lbl_version = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Version");
    $self->{iss_form_grid}->Add($iss_lbl_version, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_app_version} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "1.0.0");
    $self->{iss_form_grid}->Add($self->{iss_app_version}, 1, wxEXPAND, 0);
    
    my $iss_lbl_publisher = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Publisher");
    $self->{iss_form_grid}->Add($iss_lbl_publisher, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_app_publisher} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "Your Name or Organization");
    $self->{iss_form_grid}->Add($self->{iss_app_publisher}, 1, wxEXPAND, 0);
    
    my $iss_lbl_appid = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "AppId (GUID)");
    $self->{iss_form_grid}->Add($iss_lbl_appid, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_appid_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{iss_form_grid}->Add($self->{iss_appid_row}, 1, wxEXPAND, 0);
    
    $self->{iss_appid} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "{{A4F83C2D-9C44-4F6D-A8E2-9F7C3B6D21F0}}");
    $self->{iss_appid_row}->Add($self->{iss_appid}, 1, wxEXPAND, 0);
    
    $self->{iss_btn_gen_guid} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Generate");
    $self->{iss_appid_row}->Add($self->{iss_btn_gen_guid}, 0, wxEXPAND|wxLEFT, 6);
    
    my $iss_lbl_dist_exe = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Dist EXE Path");
    $self->{iss_form_grid}->Add($iss_lbl_dist_exe, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_dist_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{iss_form_grid}->Add($self->{iss_dist_row}, 1, wxEXPAND, 0);
    
    $self->{iss_dist_exe_path} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "..\\dist\nhc-explorer.exe");
    $self->{iss_dist_row}->Add($self->{iss_dist_exe_path}, 1, wxEXPAND, 0);
    
    $self->{iss_btn_browse_dist} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Browse\N{U+2026}");
    $self->{iss_dist_row}->Add($self->{iss_btn_browse_dist}, 0, wxEXPAND|wxLEFT, 6);
    
    my $iss_lbl_outputdir = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "OutputDir");
    $self->{iss_form_grid}->Add($iss_lbl_outputdir, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_outdir_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{iss_form_grid}->Add($self->{iss_outdir_row}, 1, wxEXPAND, 0);
    
    $self->{iss_output_dir} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "..\\release");
    $self->{iss_outdir_row}->Add($self->{iss_output_dir}, 1, wxEXPAND, 0);
    
    $self->{iss_btn_browse_outdir} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Browse\N{U+2026}");
    $self->{iss_outdir_row}->Add($self->{iss_btn_browse_outdir}, 0, wxEXPAND|wxLEFT, 6);
    
    my $iss_lbl_outputbase = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "OutputBaseFilename");
    $self->{iss_form_grid}->Add($iss_lbl_outputbase, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_output_base} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "nhc-explorer-setup");
    $self->{iss_form_grid}->Add($self->{iss_output_base}, 1, wxEXPAND, 0);
    
    my $iss_lbl_icon = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Icon (.ico)");
    $self->{iss_form_grid}->Add($iss_lbl_icon, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_icon_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{iss_form_grid}->Add($self->{iss_icon_row}, 1, wxEXPAND, 0);
    
    $self->{iss_icon_path} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "");
    $self->{iss_icon_row}->Add($self->{iss_icon_path}, 1, wxEXPAND, 0);
    
    $self->{iss_btn_browse_icon} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Browse\N{U+2026}");
    $self->{iss_icon_row}->Add($self->{iss_btn_browse_icon}, 0, wxEXPAND|wxLEFT, 6);
    
    my $iss_lbl_scope = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Install Scope");
    $self->{iss_form_grid}->Add($iss_lbl_scope, 0, wxALIGN_CENTER_VERTICAL, 0);
    
    $self->{iss_install_scope} = Wx::Choice->new($self->{notebook_1_pane_3}, wxID_ANY, wxDefaultPosition, wxDefaultSize, ["Per-user (PrivilegesRequired=lowest)", "All users (admin)"], );
    $self->{iss_install_scope}->SetSelection(0);
    $self->{iss_form_grid}->Add($self->{iss_install_scope}, 1, wxEXPAND, 0);
    
    my $iss_lbl_options = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Options");
    $self->{iss_left_sizer}->Add($iss_lbl_options, 0, wxEXPAND|wxTOP, 8);
    
    $self->{iss_opt_sizer} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{iss_left_sizer}->Add($self->{iss_opt_sizer}, 0, wxEXPAND, 0);
    
    $self->{iss_chk_desktop_icon} = Wx::CheckBox->new($self->{notebook_1_pane_3}, wxID_ANY, "Add Desktop Icon task");
    $self->{iss_chk_desktop_icon}->SetValue(1);
    $self->{iss_opt_sizer}->Add($self->{iss_chk_desktop_icon}, 0, wxEXPAND, 0);
    
    $self->{iss_chk_launch} = Wx::CheckBox->new($self->{notebook_1_pane_3}, wxID_ANY, "Launch after install (postinstall)");
    $self->{iss_chk_launch}->SetValue(1);
    $self->{iss_opt_sizer}->Add($self->{iss_chk_launch}, 0, wxEXPAND, 0);
    
    $self->{iss_chk_kill_running} = Wx::CheckBox->new($self->{notebook_1_pane_3}, wxID_ANY, "Kill running app on upgrade (taskkill in [Code])");
    $self->{iss_chk_kill_running}->SetValue(1);
    $self->{iss_opt_sizer}->Add($self->{iss_chk_kill_running}, 0, wxEXPAND, 0);
    
    $self->{iss_btn_row} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{iss_left_sizer}->Add($self->{iss_btn_row}, 0, wxEXPAND|wxTOP, 10);
    
    $self->{iss_btn_generate} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Generate Preview");
    $self->{iss_btn_row}->Add($self->{iss_btn_generate}, 1, wxEXPAND, 0);
    
    $self->{iss_btn_save} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Save .iss\N{U+2026}");
    $self->{iss_btn_row}->Add($self->{iss_btn_save}, 0, wxEXPAND|wxLEFT, 6);
    
    $self->{iss_btn_compile} = Wx::Button->new($self->{notebook_1_pane_3}, wxID_ANY, "Compile");
    $self->{iss_btn_row}->Add($self->{iss_btn_compile}, 0, wxEXPAND|wxLEFT, 6);
    
    $self->{iss_left_sizer}->Add(10, 10, 1, wxEXPAND, 0);
    
    $self->{iss_right_sizer} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{iss_main_sizer}->Add($self->{iss_right_sizer}, 1, wxALL|wxEXPAND, 6);
    
    my $iss_lbl_preview = Wx::StaticText->new($self->{notebook_1_pane_3}, wxID_ANY, "Preview (.iss)");
    $self->{iss_right_sizer}->Add($iss_lbl_preview, 0, wxEXPAND, 0);
    
    $self->{iss_preview} = Wx::TextCtrl->new($self->{notebook_1_pane_3}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, wxTE_BESTWRAP|wxTE_MULTILINE|wxTE_RICH2);
    $self->{iss_preview}->SetMinSize(Wx::Size->new(520, 1100));
    $self->{iss_right_sizer}->Add($self->{iss_preview}, 1, wxEXPAND|wxTOP, 6);
    
    $self->{notebook_1_Help} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_Help}, "Help");
    
    $self->{iss_form_grid}->AddGrowableCol(1);
    
    $self->{notebook_1_pane_3}->SetSizer($self->{iss_main_sizer});
    
    $self->{notebook_1_pane_1}->SetSizer($self->{sizer_2});
    
    $self->{panel_1}->SetSizer($self->{sizer_1});
    
    $self->Layout();
    Wx::Event::EVT_MENU($self, $self->{Open}->GetId, $self->can('select_perl_script'));
    Wx::Event::EVT_MENU($self, $self->{Exit}->GetId, $self->can('DoQuit'));
    Wx::Event::EVT_MENU($self, $self->{Aboutt}->GetId, $self->can('show_license_dialog'));
    Wx::Event::EVT_BUTTON($self, $self->{button_browse_pl}->GetId, $self->can('select_perl_script'));
    Wx::Event::EVT_BUTTON($self, $self->{button_3}->GetId, $self->can('run_pp_autolink'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_gen_guid}->GetId, $self->can('generate_iss_appid_guid'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_browse_dist}->GetId, $self->can('select_iss_dist_exe'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_browse_outdir}->GetId, $self->can('select_iss_output_dir'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_browse_icon}->GetId, $self->can('select_iss_icon_file'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_generate}->GetId, $self->can('generate_iss_preview'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_save}->GetId, $self->can('save_iss_file'));
    Wx::Event::EVT_BUTTON($self, $self->{iss_btn_compile}->GetId, $self->can('compile_iss_file'));

    # end wxGlade

    # ----- background worker comms -----
    $self->{_q}     = Thread::Queue->new();
    $self->{_timer} = Wx::Timer->new($self, wxID_ANY);
    Wx::Event::EVT_TIMER($self, $self->{_timer}, sub { $self->_drain_worker_queue });
    $self->{_timer}->Start(100); # 100ms poll
    # -----------------------------------
    return $self;

}

sub _append_io {
    my ($self, $text) = @_;
    return unless defined $text && length $text;

    $self->{txt_cmd_io}->AppendText($text);
    $self->{txt_cmd_io}->ShowPosition($self->{txt_cmd_io}->GetLastPosition);
}

sub _drain_worker_queue {
    my ($self) = @_;
    my $q = $self->{_q} or return;

    while (defined(my $msg = $q->dequeue_nb)) {
        if (ref($msg) eq 'HASH' && ($msg->{type} // '') eq 'DONE') {
            $self->_append_io("\n[done] exit_code=$msg->{exit_code}\n");
            $self->{button_3}->Enable(1);
            next;
        }
        $self->_append_io($msg);
    }
}

sub _get_perl_root {
    my $perl_path = $^X;  # full path to running perl.exe
    my ($volume, $dirs, $file) = File::Spec->splitpath($perl_path);
    my @parts = File::Spec->splitdir($dirs);
    
    # Remove \perl\bin\
    pop @parts; # bin
    pop @parts; # perl
    
    my $perl_root = File::Spec->catdir($volume, @parts);
    return $perl_root;
}

sub DoQuit {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::DoQuit <event_handler>
    # end wxGlade
    $self->Close;
}

sub show_license_dialog {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::show_license_dialog <event_handler>
    warn "Event handler (show_license_dialog) not implemented";
    $event->Skip;
    # end wxGlade
}

sub select_perl_script {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::select_perl_script <event_handler>
    # end wxGlade

    my $dlg = Wx::FileDialog->new(
        $self,
        "Select Perl Script",
        "", "",
        join('|',
            "Perl scripts (*.pl)", "*.pl",
            "Perl modules (*.pm)", "*.pm",
            "Extensionless files (*)", "*",
            "Perl-related (*.pl;*.pm;*)", "*.pl;*.pm;*",
            "All files (*.*)", "*.*",
        ),
        Wx::wxFD_OPEN() | Wx::wxFD_FILE_MUST_EXIST()
    );

    if ($dlg->ShowModal == Wx::wxID_OK()) {
        my $path = $dlg->GetPath;
        $self->{perl_script_path}->SetValue($path);
        $self->_append_io("Selected: $path\n");
    }

    $dlg->Destroy;
}

sub run_pp_autolink {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::run_pp_autolink <event_handler>
    # end wxGlade

    my $script = $self->{perl_script_path}->GetValue // '';
    $script =~ s/^\s+|\s+$//g;
    my $exe = $script;
    $exe =~ s/\.pl//g;
    $exe .= ".exe";

    if (!$script) {
        $self->_append_io("[error] No .pl selected.\n");
        return;
    }
    if (!-f $script) {
        $self->_append_io("[error] File not found: $script\n");
        return;
    }

    $script = Cwd::abs_path($script) || $script;

    $self->{button_3}->Enable(0);
    $self->_append_io("\n=== Starting pp_ autolink scan ===\n\n");

    my $q = $self->{_q};

    threads->create(sub {
        my ($script_path, $qref) = @_;

        $qref->enqueue("[worker] thread started\n\n");

        # Check pp is runnable
        my $pp_ver = `pp --version 2>&1`;
        my $pp_rc  = $? >> 8;
        $qref->enqueue("[worker] pp --version rc=$pp_rc\n$pp_ver");

        if ($pp_rc != 0) {
            $qref->enqueue("[worker][error] 'pp_autolink' command failed. Is PAR::Packer installed and on PATH?\n");
            $qref->enqueue({ type => 'DONE', exit_code => $pp_rc });
            return;
        }

        my @cmd = qw/pp_autolink -o tmp.exe/;
        push @cmd, $script_path;

        my $pretty = join(' ', map { $_ =~ /\s/ ? qq{"$_"} : $_ } @cmd);
        $qref->enqueue("[worker] cmd: $pretty\n");

        my $cmdline = $pretty . " 2>&1";

        $qref->enqueue("\n=== Finding DLLs and generating Makefile ===\n");

        my $exit = 0;
        if (open(my $fh, "$cmdline |")) {
            $qref->enqueue("[worker] pipe opened, reading output...\n");

            my $line_count = 0;
            my $CMD_line = "";
            while (my $line = <$fh>) {
                $line_count++;
                $qref->enqueue($line);
                if ($line =~ m/^CMD:/) {
                  $CMD_line = $line;
                }
            }

            my $perl_path = $^X;  # full path to running perl.exe
            
            my ($volume, $dirs, $file) = File::Spec->splitpath($perl_path);
            my @parts = File::Spec->splitdir($dirs);
            
            # Remove \perl\bin\
            pop @parts;   # bin
            pop @parts;   # perl
            pop @parts;
            push @parts, "c", "bin";
            my $filter = $volume . join("/", @parts);
            my $perl_root = lc File::Spec->catdir($volume, @parts);
            my @cmd = split / /, $CMD_line;
            my @filtered_libs = grep { m/\Q$filter\E/i } @cmd;
            
            $qref->enqueue("\n=== Perl moduled DLLs to include ===\n\n");

            my $wxpar = "wxpar -o $exe";
            foreach my $lib (@filtered_libs) {
              $wxpar .= " --link $lib ";
              $qref->enqueue("$lib\n");
            }

            $wxpar .= " $script --gui";

            $qref->enqueue("\n=== Makefile with 'wxpar' command ===\n\n");
            
            $wxpar =~ s/\\/\//g;
            $wxpar =~ s/$filter/\$\(CBIN\)/gi;

# TODO: make paths for $exe relative ...

            my $makefile = <<EOF;
# -- BEGIN MAKEFILE --

CBIN    := "$perl_root"
DIST    := dist
RELEASE := release

clean:
	\@if exist dist\* del /Q /F dist\* 2>NUL
	\@if exist release\* del /Q /F release\* 2>NUL

all: exe

exe: prepdirs
	$wxpar
	\@move /Y $exe dist\

prepdirs:
	\@if not exist \$(DIST) mkdir \$(DIST)
	\@if not exist \$(RELEASE) mkdir \$(RELEASE)
# -- END MAKEFILE --

EOF
            $qref->enqueue("$makefile");

            close($fh);
            $exit = $? >> 8;
            $qref->enqueue("[worker] pipe closed, lines=$line_count, rc=$exit\n");
        } else {
            $qref->enqueue("[worker][error] failed to run command pipe: $!\n");
            $exit = 127;
        }

        $qref->enqueue({ type => 'DONE', exit_code => $exit });
        return;
    }, $script, $q)->detach();
}


sub generate_iss_appid_guid {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::generate_iss_appid_guid <event_handler>
    warn "Event handler (generate_iss_appid_guid) not implemented";
    $event->Skip;
    # end wxGlade
}


sub select_iss_dist_exe {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::select_iss_dist_exe <event_handler>
    warn "Event handler (select_iss_dist_exe) not implemented";
    $event->Skip;
    # end wxGlade
}


sub select_iss_output_dir {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::select_iss_output_dir <event_handler>
    warn "Event handler (select_iss_output_dir) not implemented";
    $event->Skip;
    # end wxGlade
}


sub select_iss_icon_file {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::select_iss_icon_file <event_handler>
    warn "Event handler (select_iss_icon_file) not implemented";
    $event->Skip;
    # end wxGlade
}


sub generate_iss_preview {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::generate_iss_preview <event_handler>
    warn "Event handler (generate_iss_preview) not implemented";
    $event->Skip;
    # end wxGlade
}


sub save_iss_file {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::save_iss_file <event_handler>
    warn "Event handler (save_iss_file) not implemented";
    $event->Skip;
    # end wxGlade
}


sub compile_iss_file {
    my ($self, $event) = @_;
    # wxGlade: MyFrame::compile_iss_file <event_handler>
    warn "Event handler (compile_iss_file) not implemented";
    $event->Skip;
    # end wxGlade
}

# end of class MyFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame = MyFrame->new();

    $self->SetTopWindow($frame);
    $frame->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
